# Generated by Django 5.1.5 on 2025-03-23 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_city_remove_contact_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='contact',
            name='leasing_advance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Первоначальный взнос, %'),
        ),
        migrations.AddField(
            model_name='contact',
            name='leasing_monthly_payment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ежемесячный платеж'),
        ),
        migrations.AddField(
            model_name='contact',
            name='leasing_payment_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип платежей'),
        ),
        migrations.AddField(
            model_name='contact',
            name='leasing_term',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок лизинга, мес.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='processing', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='car_id',
            field=models.IntegerField(verbose_name='ID техники'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='car_title',
            field=models.CharField(max_length=100, verbose_name='Название техники'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer_need',
            field=models.CharField(max_length=100, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, verbose_name='ID пользователя'),
        ),
    ]
