# Generated by Django 5.1.5 on 2025-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_options_contact_leasing_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='staff_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администратора'),
        ),
    ]
