# Generated by Django 5.1.5 on 2025-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_staff_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='leasing_full_payment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Полная сумма'),
        ),
    ]
