# Generated by Django 5.1.5 on 2025-02-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Machinery',
        ),
    ]
