# Generated by Django 5.1.5 on 2025-02-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_car_machinery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machinery',
            new_name='Machineryy',
        ),
    ]
