# Generated by Django 5.1.5 on 2025-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_baler_harrow_harvester_mower_plow_seeder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seeder',
            old_name='fert_tank',
            new_name='fert_tank_capacity',
        ),
        migrations.RenameField(
            model_name='seeder',
            old_name='seed_tank',
            new_name='seed_tank_capacity',
        ),
        migrations.RemoveField(
            model_name='tractor',
            name='transmission',
        ),
        migrations.AddField(
            model_name='baler',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Вместимость (л)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tractor',
            name='transmission_type',
            field=models.CharField(choices=[('manual', 'Механическая'), ('auto', 'Автоматическая')], default=0, verbose_name='Тип КПП'),
            preserve_default=False,
        ),
    ]
