# Generated by Django 5.1.5 on 2025-02-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_machinery_manufacturer_machinery_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='engine_volume',
            field=models.FloatField(default=0, verbose_name='Объём двигателя (л)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinery',
            name='machinery_type',
            field=models.CharField(choices=[('Tractor', 'Трактор'), ('Harvester', 'Комбайн'), ('SelfPropelledSprayer', 'Опрыскиватель самоходный'), ('Plow', 'Плуг'), ('Seeder', 'Сеялка'), ('Harrow', 'Борона'), ('TrailedSprayer', 'Опрыскиватель прицепной'), ('Mower', 'Косилка прицепная'), ('Baler', 'Пресс-подборщик')], editable=False, max_length=50),
        ),
    ]
