# Generated by Django 5.1.5 on 2025-02-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_harvester_engine_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfpropelledsprayer',
            name='engine_volume',
            field=models.FloatField(default=0, verbose_name='Объём двигателя (л)'),
            preserve_default=False,
        ),
    ]
