# Generated by Django 5.1.5 on 2025-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_selfpropelledsprayer_engine_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plow',
            name='depth',
        ),
        migrations.AlterField(
            model_name='selfpropelledsprayer',
            name='tank_capacity',
            field=models.IntegerField(verbose_name='Объём бака удобрений (л)'),
        ),
    ]
