# Generated by Django 5.1.5 on 2025-03-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_plow_depth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinery',
            old_name='car_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='machinery',
            old_name='car_photo_1',
            new_name='photo_1',
        ),
        migrations.RenameField(
            model_name='machinery',
            old_name='car_photo_2',
            new_name='photo_2',
        ),
        migrations.RenameField(
            model_name='machinery',
            old_name='car_photo_3',
            new_name='photo_3',
        ),
        migrations.RenameField(
            model_name='machinery',
            old_name='car_photo_4',
            new_name='photo_4',
        ),
    ]
