# Generated by Django 5.1.5 on 2025-03-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_rename_car_photo_machinery_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeder',
            name='seed_type',
            field=models.CharField(choices=[('grain', 'Зерновая'), ('rowcrop', 'Пропашная'), ('universal', 'Универсальная')], default=1, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
