# Generated by Django 5.1.5 on 2025-03-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_seeder_seed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plow',
            name='width',
            field=models.FloatField(verbose_name='Ширина (м)'),
        ),
    ]
