# Generated by Django 5.1.5 on 2025-03-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_plow_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeder',
            name='width',
            field=models.FloatField(verbose_name='Ширина захвата (м)'),
        ),
    ]
