# Generated by Django 5.1.5 on 2025-03-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_seeder_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='baler',
            name='width',
            field=models.FloatField(default=1, verbose_name='Ширина захвата (м)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harrow',
            name='width',
            field=models.FloatField(verbose_name='Ширина захвата (м)'),
        ),
        migrations.AlterField(
            model_name='mower',
            name='width',
            field=models.FloatField(verbose_name='Ширина захвата (м)'),
        ),
        migrations.AlterField(
            model_name='selfpropelledsprayer',
            name='width',
            field=models.FloatField(verbose_name='Ширина обработки (м)'),
        ),
        migrations.AlterField(
            model_name='trailedsprayer',
            name='width',
            field=models.FloatField(verbose_name='Ширина обработки (м)'),
        ),
    ]
