# Generated by Django 5.1.5 on 2025-03-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_baler_width_alter_harrow_width_alter_mower_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baler',
            name='capacity',
        ),
        migrations.AddField(
            model_name='baler',
            name='min_power',
            field=models.IntegerField(default=1, verbose_name='Мин. мощность трактора (л.с.)'),
            preserve_default=False,
        ),
    ]
