# Generated by Django 5.1.5 on 2025-03-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_remove_baler_capacity_baler_min_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='drive_type',
            field=models.CharField(choices=[('wheeled_awd', 'Колёсный, полный'), ('wheeled_rwd', 'Колёсный, задний'), ('tracked', 'Гусеничный')], verbose_name='Тип'),
        ),
    ]
