# Generated by Django 5.1.5 on 2025-03-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_alter_baler_bale_size_alter_machinery_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
