# Generated by Django 5.1.5 on 2025-03-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_alter_machinery_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='tow_class',
            field=models.FloatField(choices=[(0.6, 'Класс 0.6'), (0.9, 'Класс 0.9'), (1.4, 'Класс 1.4'), (2, 'Класс 2'), (3, 'Класс 3'), (4, 'Класс 4'), (5, 'Класс 5'), (6, 'Класс 6')], verbose_name='Тяговый класс'),
        ),
    ]
