# Generated by Django 5.1.5 on 2025-03-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_alter_tractor_tow_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baler',
            name='bale_size',
        ),
    ]
