# Generated by Django 5.1.5 on 2025-03-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_baler_bale_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mower',
            name='min_power',
            field=models.IntegerField(default=50, verbose_name='Мин. мощность трактора (л.с.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mower',
            name='productivity',
            field=models.IntegerField(default=4, verbose_name='Макс. роизводительность (га/час))'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mower',
            name='rotation_speed',
            field=models.IntegerField(default=2850, verbose_name='Скорость вращения (об/мин)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baler',
            name='productivity',
            field=models.IntegerField(verbose_name='Макс. производительность (тюков/час)'),
        ),
    ]
