# Generated by Django 5.1.5 on 2025-03-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_mower_min_power_mower_productivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mower',
            name='productivity',
            field=models.FloatField(verbose_name='Макс. роизводительность (га/час))'),
        ),
    ]
