# Generated by Django 5.1.5 on 2025-03-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_alter_mower_productivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfpropelledsprayer',
            name='width',
        ),
        migrations.AddField(
            model_name='harrow',
            name='max_depth',
            field=models.IntegerField(default=18, verbose_name='Максимальная глубина обработки (см)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harrow',
            name='min_depth',
            field=models.IntegerField(default=7, verbose_name='Минимальная глубина обработки (см)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harrow',
            name='productivity',
            field=models.IntegerField(default=10.8, verbose_name='Макс. производительность (га/час)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selfpropelledsprayer',
            name='maxwidth',
            field=models.FloatField(default=48, verbose_name='Ширина обработки до, м'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selfpropelledsprayer',
            name='minwidth',
            field=models.FloatField(default=21, verbose_name='Ширина обработки от, м'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selfpropelledsprayer',
            name='pump_productivity',
            field=models.IntegerField(default=520, verbose_name='Макс. производительность насоса (л/мин)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailedsprayer',
            name='maxwidth',
            field=models.FloatField(default=1, verbose_name='Ширина обработки до, м'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailedsprayer',
            name='minwidth',
            field=models.FloatField(default=24, verbose_name='Ширина обработки от, м'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailedsprayer',
            name='pump_productivity',
            field=models.IntegerField(default=250, verbose_name='Макс. производительность насоса (л/мин)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mower',
            name='productivity',
            field=models.FloatField(verbose_name='Макс. производительность (га/час))'),
        ),
    ]
