# Generated by Django 5.1.5 on 2025-03-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_alter_selfpropelledsprayer_maxwidth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailedsprayer',
            name='width',
        ),
    ]
