# Generated by Django 5.1.5 on 2025-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_mower_mower_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='drive_type',
            field=models.CharField(choices=[('wheeled_awd', 'Колёсный, полный привод'), ('wheeled_rwd', 'Колёсный, задний привод'), ('tracked', 'Гусеничный')], verbose_name='Тип'),
        ),
    ]
