# Generated by Django 5.1.5 on 2025-04-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_alter_tractor_drive_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='manufacturer',
            field=models.CharField(max_length=30, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='model_name',
            field=models.CharField(max_length=30, verbose_name='Название модели'),
        ),
    ]
